### ISSUE TITLE
SourceSansVariable 1.020 may have issues with mk2mk

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-sans#150]
1.020 of Source Sans Variable has several glyphs which do not behave properly in PS, AI, or AxisPraxis when either pre-built instance weights are changed or when sliders are used. Images attached for both Photoshop:
![sourcesansvariable1020_mk2mk](https://user-images.githubusercontent.com/7459753/47669351-feef2500-db67-11e8-8db3-75337dfe5852.jpg)

and Illustrator:
![ai_ssvariable1020_mk2mk](https://user-images.githubusercontent.com/7459753/47669368-06aec980-db68-11e8-8288-5ca124adcb61.jpg)

In Axis-Praxis, these display as solid diamonds with question marks.

**Comment by miguelsousa** [comment]
It may have something to do with this issue https://github.com/fonttools/fonttools/issues/1328

**Comment by erniemarch** [comment]
I note also that the glyphs appear correctly in the glyph palettes of both AI and PS, but mis-behave in an actual document.

**Comment by pauldhunt** [comment]
@erniemarch can you tell me what this has to do with mk2mk?

**Comment by pauldhunt** [comment]
it seems the characters being affected are precomposed ❝ligatures❞ that do not have Unicode values of their own. How are you entering these sequences? Are you entering unicode strings? or doing copy/paste from some glyph dumps? or something else?

**Comment by erniemarch** [comment]
inserted from the glyph palette.

**Comment by pauldhunt** [comment]
I’m going to chalk this one up to input issues and not a font bug.
