### ISSUE TITLE
Add support for macron over macron

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans#159]
This combination appeared in a Bible translated in Jian’ou dialect of Min Chinese.
![Sample](https://upload.wikimedia.org/wikipedia/commons/1/1b/JianningBible1.gif)
However it doesn’t works well with Source Sans Pro.
>ā̄ē̄ī̄ō̄ū̄

![default](https://user-images.githubusercontent.com/10364351/49958165-e5305400-ff01-11e8-9c80-a8527ea4414c.PNG)
See: https://books.google.com/books?id=WCYMAwAAQBAJ&pg=PA559&lpg=PA559&dq=kienning+romanized&source=bl&ots=F7RIDpm5PW&sig=P0cHBakCJK0EOemLoy6GgIYi_74&hl=en&sa=X&ei=4f7sVJSrA9Xv8gXCtIKoAw&ved=0CC4Q6AEwBA#v=onepage&q=kienning%20romanized&f=false

**Comment by pauldhunt** [comment]
Will update mark-to-mark positioning in next release.

**Comment by pauldhunt** [comment]
I was unable to get to this issue for the upcoming release, but will keep on my to-do list for the near future.

**Comment by pauldhunt** [comment]
For future reference, here is some Unicode text (taken from the image above) for reference and testing:
CHŌ̤̄NG SĪ̄ GĪ̄.
1 Dĭ buōi-chǒ gâ̤ sî-hē Ciōng-Dī̄ kṳé tínt bī dī.
2 Dī sī lòng kóng iǎng ō̤̄ng gâ̤; chéng tâing gâ̤ sù-cài 
dú sī ú-ō̤̄ng. Ciōng-Dī gâ̤ Sěng hū dāu iŏ̤ng sṳ̌
3 mi̅ng. Cio̅ng-Di̅̅ ua̅, Nio̅ng iǔ guáng: ciū iǔ guáng
4 hīng chṳ̆ lâ̤. Ciōng-Dī chū iŏ̤ng guáng sī děng
hǎu: Ciōng-Dī ciū nà iŏ̤ng guáng iáu o̤̅̅ng bṳ́ing-kṳé.

**Comment by moyogo** [comment]
> For future reference, here is some Unicode text (taken from the image above) for reference and testing:
> CHŌ̤̄NG SĪ̄ GĪ̄.
> 1 Dĭ buōi-chǒ gâ̤ sî-hē Ciōng-Dī̄ kṳé tínt bī dī.
> 2 Dī sī lòng kóng iǎng ō̤̄ng gâ̤; chéng tâing gâ̤ sù-cài
> dú sī ú-ō̤̄ng. Ciōng-Dī gâ̤ Sěng hū dāu iŏ̤ng sṳ̌
> 3 mi̅ng. Cio̅ng-Di̅̅ ua̅, Nio̅ng iǔ guáng: ciū iǔ guáng
> 4 hīng chṳ̆ lâ̤. Ciōng-Dī chū iŏ̤ng guáng sī děng
> hǎu: Ciōng-Dī ciū nà iŏ̤ng guáng iáu o̤̅̅ng bṳ́ing-kṳé.

The U+0305 COMBINING OVERLINE should be U+0304 COMBINING MACRON:
CHŌ̤̄NG SĪ̄ GĪ̄.
1 Dĭ buōi-chǒ gâ̤ sî-hē Ciōng-Dī̄ kṳé tínt bī dī.
2 Dī sī lòng kóng iǎng ō̤̄ng gâ̤; chéng tâing gâ̤ sù-cài
dú sī ú-ō̤̄ng. Ciōng-Dī gâ̤ Sěng hū dāu iŏ̤ng sṳ̌
**3 mīng. Ciōng-Dī̄ uā, Niōng iǔ guáng: ciū iǔ guáng**
4 hīng chṳ̆ lâ̤. Ciōng-Dī chū iŏ̤ng guáng sī děng
**hǎu: Ciōng-Dī ciū nà iŏ̤ng guáng iáu ō̤̄ng bṳ́ing-kṳé.**
