### ISSUE TITLE
Combining dot above right is conflict with other diacritics

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans#178]
The combining dot above right is added in Source Sans Pro 3.006, but the usage of this diacritic is not perfect, this mark has some inconsistency with other diacritics or without. 
The following letters can produce this problem:
```
Ó͘ ó͘ (second tone)
Ò͘ ò͘ (third tone)
Ô͘ ô͘ (fifth tone)
Ō͘ ō͘ (seventh tone)
O̍͘ o̍͘ (eighth tone)
```

BabelPad:
![1](https://user-images.githubusercontent.com/10364351/64474276-b5497080-d162-11e9-83e7-84c95cb502c7.PNG)
LbreOffice:
![2](https://user-images.githubusercontent.com/10364351/64474293-df029780-d162-11e9-9126-c0084738d49c.PNG)

See: https://commons.wikimedia.org/wiki/File:Tai-Oan-Hu-Sia-Kau-Hoe-Po.jpg
This is a photo from the 1st issue of Taiwan Church News, which has some examples for this.

**Comment by miguelsousa** [comment]
@KrasnayaPloshchad what is the desired/expected arrangement?

**Comment by miguelsousa** [comment]
Test file

```html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<style>

		@font-face{
			font-family: 'Source Sans';
			src: url('./SourceSansPro-Regular.ttf') format('truetype');
		}

		body {
			background-color: #A6A6A6;
		}

		p {
			font-family: 'Source Sans', sans-serif;
			font-size: 50pt;
			margin-top: 0;
			margin-bottom: 0;
		}

	</style>
</head>
<body>
	<p>O&#x0358;</p>
	<p>O&#x0301;&#x0358; O&#x0358;&#x0301; o&#x0301;&#x0358; o&#x0358;&#x0301; (2nd tone)</p>
	<p>O&#x0300;&#x0358; O&#x0358;&#x0300; o&#x0300;&#x0358; o&#x0358;&#x0300; (3rd tone)</p>
	<p>O&#x0302;&#x0358; O&#x0358;&#x0302; o&#x0302;&#x0358; o&#x0358;&#x0302; (5th tone)</p>
	<p>O&#x0304;&#x0358; O&#x0358;&#x0304; o&#x0304;&#x0358; o&#x0358;&#x0304; (7th tone)</p>
	<p>O&#x030D;&#x0358; O&#x0358;&#x030D; o&#x030D;&#x0358; o&#x0358;&#x030D; (8th tone)</p>
</body>
</html>
```

**Comment by KrasnayaPloshchad** [comment]
To my eyes, dot above right should be placed near the base letter and other diacritics, but not be overlap other diacritics. BTW have you saw the link from above?
![Sample](https://user-images.githubusercontent.com/10364351/64703094-4d18c880-d49b-11e9-9706-8327133a2480.png)
(This is modified from screenshot)

**Comment by miguelsousa** [comment]
Thanks for the graphic.

> BTW have you saw the link from above?

Yes, I did look at the image of a printed page you linked to, but it wasn't obvious what parts of it were important. That's why I requested additional information.

**Comment by KrasnayaPloshchad** [comment]
Here is the original file from Wikimedia Commons, you can see more details if you want to see what you need.
https://upload.wikimedia.org/wikipedia/commons/0/07/Tai-Oan-Hu-Sia-Kau-Hoe-Po.jpg

**Comment by pauldhunt** [comment]
Is it possible to get from you a full list of possible combinations with combining dot above right?

**Comment by KrasnayaPloshchad** [comment]
OK, here is the list of possible combinations:
Ó͘ `004F 0358 0301`, `004F 0301 0358`, `00D3 0358`
ó͘ `006F 0358 0301`, `006F 0301 0358`, `00F3 0358`
Ò͘ `004F 0358 0300`, `004F 0300 0358`, `00D2 0358`
ò͘ `006F 0358 0300`, `006F 0300 0358`, `00F2 0358`
Ô͘ `004F 0358 0302`, `004F 0302 0358`, `00D4 0358`
ô͘ `006F 0358 0302`, `006F 0302 0358`, `00F4 0358`
Ō͘ `004F 0358 0304`, `004F 0304 0358`, `014C 0358`
ō͘ `006F 0358 0304`, `006F 0304 0358`, `014D 0358`
O̍͘ `004F 0358 030D`, `004F 030D 0358`
o̍͘ `006F 0358 030D`, `006F 030D 0358`

**Comment by KrasnayaPloshchad** [comment]
@ButTaiwan Can you help?

**Comment by ButTaiwan** [comment]
> @ButTaiwan Can you help?

You've listed up all the combinations above.

**Comment by KrasnayaPloshchad** [comment]
Yes, it would be nice if you can contribute as a pull request.

**Comment by KrasnayaPloshchad** [comment]
@ButTaiwan So can you make contributions to this font?

**Comment by ButTaiwan** [comment]
There are also the 6th tone (U+030C) and the 9th tone (U+030B). (rarely used, but exist.)

So the full list should be:

o͘    o + U+0358
O͘    O + U+0358

ò͘ o + U+0358 + U+0300
́o͘ o + U+0358 + U+0301
ô͘ o + U+0358 + U+0302
̌o͘ o + U+0358 + U+030C
̄o͘ o + U+0358 + U+0304
̍o͘ o + U+0358 + U+030D
̋o͘ o + U+0358 + U+030B

̀O͘ O + U+0358 + U+0300
Ó͘ O + U+0358 + U+0301
Ô͘ O + U+0358 + U+0302
Ǒ͘ O + U+0358 + U+030C
Ō͘ O + U+0358 + U+0304
O̍͘ O + U+0358 + U+030D
Ő͘ O + U+0358 + U+030B

Compatibility sequences:

ó͘ U+00F3 + U+0358 / o + U+0301 + U+0358
ò͘ U+00F2 + U+0358 / o + U+0300 + U+0358
ô͘ U+00F4 + U+0358 / o + U+0302 + U+0358
ǒ͘ U+01D2 + U+0358 / o + U+030C + U+0358
ō͘ U+014D + U+0358 / o + U+0304 + U+0358
o̍͘ o + U+030D + U+0358
ő͘ U+0151 + U+0358 / o + U+030B + U+0358

Ó͘ U+00D3 + U+0358 / O + U+0301 + U+0358
Ò͘ U+00D2 + U+0358 / O + U+0300 + U+0358
Ô͘ U+00D4 + U+0358 / O + U+0302 + U+0358
Ǒ͘ U+01D1 + U+0358 / O + U+030C + U+0358
Ō͘ U+014C + U+0358 / O + U+0304 + U+0358
O̍͘ O + U+030D + U+0358
Ő͘ U+0150 + U+0358 / O + U+030B + U+0358
