### ISSUE TITLE
Request: Support for four unofficial IPA characters

### ISSUE THREAD

**Issue by throwaway571** [adobe-fonts/source-sans#195]
The characters ᵻ U+1D7B and ᵿ U+1D7F are used in some variants of the IPA, such as the one used by the Oxford English Dictionary, to represent weak unstressed vowels that can be reduced to schwa for some speakers. The examples given are _honest_ /ˈɒnᵻst/ and _July_ /dʒᵿˈlʌɪ/.

Note that these are barred versions of U+026A ɪ and U+028A ʊ, and not, as some fonts have it, of U+0131 ı and U+028B ʋ.

Added 2020-09-06: Transcriptions of Chinese languages often use two unofficial IPA symbols for the so-called “apical vowels”: ɿ U+027F and ʅ U+0285. Despite their official Unicode names, these two characters form a series, and U+0285 is in essence U+027F with a retroflex hook.

**Comment by pauldhunt** [comment]
@throwaway571 do you have any good references for the Chinese transcription characters?

**Comment by throwaway571** [comment]
@pauldhunt Here's an example from a paper by Faytak & Lin:
![image](https://user-images.githubusercontent.com/62322214/94517442-cd13ec80-01dc-11eb-9998-1919048771e8.png)

**Comment by pauldhunt** [comment]
@throwaway571 so they both descend below the baseline? got it. thanks.

**Comment by throwaway571** [comment]
@pauldhunt Well, [ɿ] has two alternative glyphs. Unicode says that the glyph with a descender is preferred, but I’ve also seen it without a descender in several publications. In any case, it shouldn’t matter; it’s the same character.

Note that, because all four of these characters are vowels, they can technically take diacritics in the IPA. I don’t think I’ve seen diacritics on the barred letters in practice, but I have seen tone diacritics above the apical vowel letters.

**Comment by throwaway571** [comment]
@pauldhunt Here is an example of a combining acute on U+0285:
![image](https://user-images.githubusercontent.com/62322214/94521389-d1db9f00-01e2-11eb-8b09-46c6bbc13d0a.png)

**Comment by pauldhunt** [comment]
it’s probably best to keep things separate if you keep adding new characters you want supported. even better would be to try to compile all of the characters you think you will need into one thread.
btw, do you have the unicode text for the IPA sample above? i’d like to try setting it in Source Sans, but i’d rather not have to set this if you have it available to you.

**Comment by throwaway571** [comment]
@pauldhunt 

[wɔ̌ t͡ʂʰʅ̄ ʨʰʲǎʷ kʰɤ̀ lì ʂʅ́ pʰí fū hʷèʲ t͡ʂ˭ʊ́ŋ ʨʰǐ láʲ]

**Comment by pauldhunt** [comment]
@throwaway571 thank you 🙏🏽
