### ISSUE TITLE
Decrease line height

### ISSUE THREAD

**Issue by t2b3** [adobe-fonts/source-sans#212]
Dear sir or madam.

I would like to suggest an improvement.
By decrasing the default line height, Source Sans may be more suitable for UI purposes, see

![image](https://user-images.githubusercontent.com/3286756/110859790-43ecff80-82bc-11eb-9eb1-4beb70b7ba61.png)

Yours sincerely,
Tobias Predel

**Comment by frankrolf** [comment]
The choice of default line height is informed by the height of accented characters, some of which will be clipped if the line height would be chaged.
MS Word is one of the few applications in which line height cannot be _de_creased, but your example above looks good considering the line length.

Closing this bug as “as designed”, please feel free to ask follow-up questions right here.
