### ISSUE TITLE
Hinting for Windows

### ISSUE THREAD

**Issue by Daymarius** [adobe-fonts/source-sans#213]
Need hinting like in 2.021 version for Windows.

**Comment by pauldhunt** [comment]
@Daymarius we’ve stopped manually hinting the TT fonts, is there functionality that you are missing from the 2.021 version that is in the newer versions? If not and if TT hinting is of a concern to you, you might consider just sticking with the old version that has the hinting that works for you?

**Comment by Daymarius** [comment]
In the old version with hinting there is no cyrillic in italics. Do not misunderstand me, I just want a good font to be even better for more people. But of course manual hinting should be done already in the final version or near the final, so that there are not many glyph changes so as not to re-hinting. Windows are very dependent on hinting.

**Comment by pauldhunt** [comment]
This is an issue that I will not be attending to in the immediate future. If anyone would like to hint the TTF fonts, I would be happy to incorporate them into this project.

**Comment by fitojb** [comment]
With ttfautohint, one just needs to play with the blue-zone values and one can achieve great results with minimal effort.

**Comment by duckbedsun** [comment]
@pauldhunt
Could you release the latest manually hinted version please?
2.020 (hinted) is available on the releases page.
I don't find 2.021.
