### ISSUE TITLE
different glyphs for tonos and oxia

### ISSUE THREAD

**Issue by ousia** [adobe-fonts/source-sans#214]
Although oxia is tonos (that is, the monotonic Greek accent is acute), all fonts that contains both accented glyphs (see below) have different inclination for both accents.

This is problematic with polytonic Greek, because both acute and grave accents are mixed,

![toss-1](https://user-images.githubusercontent.com/203767/116295528-7a61d980-a799-11eb-8877-1548a001626d.png)

![toss-2](https://user-images.githubusercontent.com/203767/116295527-79c94300-a799-11eb-8bf6-258f966e3dee.png)

![toss-3](https://user-images.githubusercontent.com/203767/116295518-78981600-a799-11eb-91da-778af9a200b1.png)

![toss-4](https://user-images.githubusercontent.com/203767/116295523-7930ac80-a799-11eb-8d6d-d9344ed4b0e6.png)

Uppercase letters are fine, but first line in lowercase letters displays the right combination (with acute) while the second line in lowercase letters shows the problem (with accent).

Since OpenType allows a local feature that replaces tonos with oxia and polytonic Greek is defined as language,  @frankrolf, 
how about the following feature for polytonic Greek in the Source typeface family?

```
feature locl {

    @tonosuppercase = [Alphatonos Epsilontonos Etatonos Iotatonos
                       Omicrontonos Omegatonos Upsilontonos];

    @tonoslowercase = [alphatonos epsilontonos etatonos iotatonos
                       iotadieresistonos omicrontonos omegatonos
                       upsilontonos upsilondieresistonos];

    @oxiauppercase = [uni1FBB uni1FC9 uni1FCB uni1FDB uni1FF9
                      uni1FFB uni1FEB];

    @oxialowercase = [uni1F71 uni1F73 uni1F75 uni1F77 uni1FD3
                      uni1F79 uni1F7D uni1F7B uni1FE3];

    script grek;

        language PGR exclude_dflt;

            lookup TonosOxia {
                sub @tonosuppercase by @oxiauppercase;
                sub @tonoslowercase by @oxialowercase;
            } TonosOxia;

} locl;
```

**Comment by pauldhunt** [comment]
@ousia I’m not sure why you’re calling out @frankrolf on this issue, but it seems like a good suggestion. Will try to get this in the next update.

**Comment by ousia** [comment]
@pauldhunt, sorry for my misunderstanding.

I thought that Frank was in charge for the Greek part of the typeface.

Congratulations for your excellent work on Source Sans.
