### ISSUE TITLE
What are /t_h_e_y etc?

### ISSUE THREAD

**Issue by projectshifter** [adobe-fonts/source-sans#217]
The most recent development builds of Source Sans 3 contain a set of 6 glyphs that look like variations on U+210B ℋ. Their glyph names are case variants of `t_h_e_y` and `t_h_e_i_r`, so I’d assume they somehow correspond to the English pronouns _they_ and _their_. 1) How do you activate them, and 2) why are they handled at the typeface level?

**Comment by pauldhunt** [comment]
These are experimental ligatures in the discretionary ligatures (`dlig`) feature that replace gendered pronouns with custom glyphs proposed by Sarah Gephart. These are off by default and can only be activated in the Source Sans fonts by turning on the feature. For more information see:
[Typographics 2018: Collaborative Digression(s) with Alicia Cheng & Sarah Gephart](https://vimeo.com/302898160)
