### ISSUE TITLE
Kerning between IPA symbols and brackets

### ISSUE THREAD

**Issue by projectshifter** [adobe-fonts/source-sans#218]
IPA transcriptions are conventionally delimited in square brackets (phonetic), slashes (phonemic) or vertical bars (morphological). A number of IPA symbols (ʃ ɗ ʄ etc.) have a hook pointing to the right that clashes with a following boundary character.

In this transcription of the Hebrew word for ‘sun’, the esh is kerned with respect to the opening bracket, but it runs together with the closing bracket:
![image](https://user-images.githubusercontent.com/79190852/118760232-4f622700-b827-11eb-833b-8594f86c8fc7.png)

**Comment by pauldhunt** [comment]
I’ll fix this for the next release.
