### ISSUE TITLE
Typo in Copyright notice of font files

### ISSUE THREAD

**Issue by SFr682k** [adobe-fonts/source-sans#223]
There’s a typo in the font files’ copyright notice (see e.g. `SourceSans3-Regular.otf`); it currently reads:
> © 2010 - 2021 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name ‘Source†.

To fix this, `\2020` (Dagger) would need to be replaced with `\2019` (Right Single Quotation Mark) in the following line:
https://github.com/adobe-fonts/source-sans/blob/ecf13e573bcce1de7c31d62c022d5830b927e20f/familynameIDs.fea#L4

**Comment by frankrolf** [comment]
@pauldhunt Unicode-escapes are no longer necessary in feature files, so it can be
`nameid 0 "© 2010 - 2021 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name ‘Source’";`
