### ISSUE TITLE
Possibly variant for ầ, ề and ồ

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans#232]
I have seen that ầ, ề and ồ may have unusual design that placed grave accent at top right of circumflex. Maybe it’s resonable to implement as character variant feature.

See: https://www.bilibili.com/video/BV1E54y1W7x1

**Comment by fitojb** [comment]
It’s not unusual at all. In fact, it’s the preferred alignment for legibility, according to https://vietnamesetypography.com/design-challenges/

**Comment by KrasnayaPloshchad** [comment]
Oh I’ve seen that variant in videos from South Vietnam era for first times.
