### ISSUE TITLE
Font name changed from Source Sans Pro to Source Sans 3 / Source Serif Pro to Source Serif 4

### ISSUE THREAD

**Issue by davidimagitech** [adobe-fonts/source-sans#233]
Font name change means that old version of the font cannot be updated in place, meaning that to take advantage of the updated fonts you'd have to update elements in graphics projects one by one, which is obviously a non-starter.

Please consider reverting to the old font names.

**Comment by davidimagitech** [comment]
Ignore, I see the name change was announced in the release notes.

A fork so that there were separate Source Sans Pro and Source Sans 4 would probably have been a better choice to make the breaking change more obvious though.

**Comment by pauldhunt** [comment]
@davidimagitech or you can stick with the old version unless you absolutely need the updates, in which case: the updates are in a new version of the software and is worth the price of the upgrade: your time swapping over to new fonts.

**Comment by frankrolf** [comment]
@davidimagitech Your point is clear, and it’s understandable why some users may be disgruntled – but ultimately, we believed this was the better way forward. See some of the reasons behind the name change in the discussion here:
https://github.com/adobe-fonts/source-serif/issues/77

**Comment by davidimagitech** [comment]
Thanks @frankrolf, I had seen the topic after my initial post and I understand the rationale, which is why I closed the issue.

As the versions will effectively separate fonts from a user's perspective (different font name, different entries in font drop down boxes), perhaps there should be separate GitHub projects for each, or at the very least a link to the last release for the named version of each (Source Sans Pro, Source Sans 3, etc.) in the READMED.md file to make it more obvious and make the most recent version of the old version easier to locate.

**Comment by frankrolf** [comment]
>  link to the last release for the named version of each
That’s not a bad idea. 😎
Thanks!
