### ISSUE TITLE
Apple PDFKit unable to render MS Word (Windows) documents

### ISSUE THREAD

**Issue by snowbanker** [adobe-fonts/source-sans#234]
Probably a mixture of issues with the above mentioned software (MS Word 365 v2111, Adobe Acrobat Pro 2020, PDFKit in iOS/iPadOS 15), but I thought I should mention it:

See sample DOCX file attached. [Wikipedia-Star_Wars_(Film).docx](https://github.com/adobe-fonts/source-sans/files/7298304/Wikipedia-Star_Wars_.Film.docx)

This is a Word document using two non-standard typefaces (SS3 Light v3.028 and, for comparison, Soleto). Numbers set to proportional spacing. SS3 set to Stylistic Set 1 (roman capital i with serifs). 

Converted to PDF using Acrobat for Word (as opposed to Word's built-in PDF engine). See attached PDF. [Wikipedia-Star_Wars_(Film).pdf](https://github.com/adobe-fonts/source-sans/files/7298302/Wikipedia-Star_Wars_.Film.pdf)

PDF file looks fine in Adobe Acrobat Reader, Windows 10/11 Preview (Explorer/Edge), and similar. However, if viewed on iPhone/iPad, the SS3 text doesn't work at all. It is rendered in another typeface entirely, and any OpenType variations like the 'i' and the proportional numbering are blank. For comparison, none of these issues appear with other typefaces, including Soleto or the typefaces included as part of Office 365. See attached screenshot. [Wikipedia-Star_Wars_(Film)-iPad](https://user-images.githubusercontent.com/90900549/136313009-7d826a9c-49fa-4b2e-adec-762cfd858b13.jpg)

(On a related note to another typeface - I don't have a sample prepared and I guess it belongs on that github page - but Noto Sans SC doesn't render either, but Noto Sans CJK SC does.)

There are no similar problems with using Microsoft Word 365 on Mac; nor with using PowerPoint 365 on Windows with SS3 (font renders correctly; Opentype features are not available in PowerPoint).  If we try and use the Word built-in PDF engine, text seems to be converted into bitmaps instead of text+embedded font subset.

Hope that is clear!

**Comment by frankrolf** [comment]
Screenshots from iPhone 12 Pro, iOS 15.0.1:
![IMG_1575](https://user-images.githubusercontent.com/2049645/136335572-faa298bc-5227-4cc1-9af4-fbc42a319d65.png)
![IMG_1574](https://user-images.githubusercontent.com/2049645/136335598-1d4ca148-613c-4788-a91c-45bb703e9419.png)

The font we’re seeing is the Apple MM replacement font, which implies the font is considered “missing” in the PDF.
Acrobat on iOS shows the document like this:
![IMG_1576](https://user-images.githubusercontent.com/2049645/136335963-f6c01bb5-cb35-47cd-976f-80959d6927d2.png)

There is something going on with the font embedding.
Other than the version number used, can you indicate if you’re using the OTF or TTF variants (and perhaps try the opposite)? I don’t think Variable Fonts are supported in MS Word, so no need to investigate in that direction.

**Comment by snowbanker** [comment]
Answering Frank's question: using SS3 Light (i.e. not variable) OTF files in Word for Windows and PowerPoint for Windows (particularly to retain OpenType features as detailed above). Oddly, there is no problem in a PowerPoint converted to PDF using the exact same method in the same version of Office. So it kinda feels like there's  a minor element that iOS 15 looks for that doesn't make it through in a Word conversion with SS3, but does make it through with other fonts (Soleto in the example, but it works with others too).
