### ISSUE TITLE
Romanian ș and ț look malformed

### ISSUE THREAD

**Issue by JapanYoshi** [adobe-fonts/source-sans#237]
The Romanian alphabet has 5 special characters, two of which are "S with comma accent below" and "T with comma accent below". However, those two letters have a long history of being confused as having a cedilla below.

Most Google Fonts have the Romania letters with the correct comma shape that is clearly distinct from the cedilla. (Note: The sample text reads "In 1 km, exit the highway to Gölbaşı (a town in Ankara, Turkey).")
![image](https://user-images.githubusercontent.com/8707990/144959505-93d6f173-ecb8-4f0a-bb03-776fea9d20bf.png)
![image](https://user-images.githubusercontent.com/8707990/144959468-0c9a60da-f060-4734-8cf6-231861e827fd.png)
![image](https://user-images.githubusercontent.com/8707990/144959588-86f6ee2b-895d-4ca2-b69a-6ce2f81dd110.png)

However, Source Sans Pro has the comma accents malformed, like a cedilla with the top cut off instead of a comma.
![image](https://user-images.githubusercontent.com/8707990/144959448-292e5a9d-d186-4055-ab46-7f0148c919ff.png)

**Comment by moyogo** [comment]
The comma below is not ambiguous and should look like a comma in ȘșȚț or in U+0326 by itself or when combined with any other character.

Before S and T characters with comma below were added to Unicode, S and T characters with cedilla were meant to be used in Romanian and were supposed to have the comma shape in modern Romanian, but not necessarily in other languages.
After S and T characters with comma below were added to Unicode, they were supposed to be used in Romanian instead.
The comma shape is strongly preferred, hence the addition of the separate characters.

The cedilla is an ambiguous diacritic in Unicode. It can look like the fully attached traditional cedilla, a fully attached right hook, a detached right hook or a comma. Some languages have a required shape, like Latvian with the comma shape on ĢģĶķĻļŅņŖŗ. Unicode shows the comma shape for those primarily Latvian characters. Some other languages have preferred shapes or are flexible on what shape can be used. Unicode shows the fully attached traditional cedilla for the other characters with cedilla.

That said, what the comma below should looks like when designed to fit in the font metrics may be closer to the current detached hook shape than to the shape of the comma.

**Comment by JapanYoshi** [comment]
I’ve looked at the other characters with the comma accent, and I think the core problem is that Source Sans’ comma accent is malformed in general. The Latvian language, as you’ve pointed out, requires a comma shape for its “cedilla” letters, and the current Source Sans design pretty much clearly violates that required shape in all ways but that it’s detached from the main body.

![Screenshot_20220317_223929](https://user-images.githubusercontent.com/8707990/158821336-a493f00f-0699-4692-888d-efdf72995643.png)
![Screenshot_20220317_223946](https://user-images.githubusercontent.com/8707990/158821341-a61a2156-bf3b-4b3f-ae50-55f26dad5c70.png)
![Screenshot_20220317_224005](https://user-images.githubusercontent.com/8707990/158821345-a18ff701-1339-4d7d-a11b-f748359faf40.png)
![Screenshot_20220317_224025](https://user-images.githubusercontent.com/8707990/158821353-3c856604-8935-4aa4-91b2-e8ef55975733.png)
![Screenshot_20220317_224039](https://user-images.githubusercontent.com/8707990/158821355-13895413-50b9-4504-b763-730bc6e153d9.png)

It’s true that the S and T with cedilla were ambiguous in the early days of text encoding. However, *as it stands now,* the Unicode code points for S and T with comma below are preferred or required over those with cedilla for Romanian text.

**They are now separate characters with separate designs and separate purposes.** Having the comma accent look like cedilla from reading distance could hamper understandings

ŞşŢţ - Used in Turkish.
ȘșȚț - Used in Romanian.
