### ISSUE TITLE
Feature request: more explicit capital I

### ISSUE THREAD

**Issue by kiwi0fruit** [adobe-fonts/source-sans#241]
Please consider adding (maybe in a stylistic set) more explicit letter I. For example [Noto Sans](https://fonts.google.com/?preview.text=Iulius%20lulz%20Julius&preview.text_type=custom&preview.layout=row&preview.size=32&query=Noto+Sans+Display) has it. But I guess it has not the most optimal design for it. More explicit capital I may be useful for classical Latin like [Iulius](https://en.wiktionary.org/wiki/Iulius). Source Sans already has distinct small l that mitigates misreads. But reader habits may still interpret Iu (IU) as lu (LU). I suggest the following letter form for capital I: flipped horizontally small l with height adjusted. This way it resembles capital J but like a not fully developed form. This mimics etymology of the letter J which historically derived from I (i).
|  |  |  |
| - | - |- |
| ![iulius](https://user-images.githubusercontent.com/19735117/163833895-234355c4-114b-4059-a164-84a150c67fef.png) | ![iulius_orig](https://user-images.githubusercontent.com/19735117/163833920-5c96c369-ef6e-4d74-865e-75bc270c1c42.png) | ![iulius_orig](https://user-images.githubusercontent.com/19735117/163833920-5c96c369-ef6e-4d74-865e-75bc270c1c42.png) |

**Comment by kiwi0fruit** [comment]
It's quite common for [handwriting fonts](https://fonts.google.com/?preview.text=Iulius%20lulz%20Julius&preview.text_type=custom&preview.layout=row&preview.size=32&category=Handwriting) to have this same approach where capital I and capital J look alike but J is more "pronounced".

**Comment by pauldhunt** [comment]
The stylistic set you are looking for is Sytlistic Set #1 labeled "Serifed I" in programs that can expose the stylistic set names. You can also access this character via its unicode point: U+A7AE: Ɪ.

**Comment by kiwi0fruit** [comment]
Thank you!

**Comment by kiwi0fruit** [comment]
@pauldhunt Thank you again. I'll just speak up. May be you'll consider it. May be not. Using *serifed* I in a *sans-serif* font feels suboptimal. But at the moment it's a best solution for ambiguity. I played with J-like capital I described above and it's a poor solution in general. In abbreviations it looks bad. But where it looks OK is before lowercase vowel letters. If to implement ligatures for Ia,Iu,Io,Ie,Iy,Ii that would have J-like capital I then it may fix ambiguity and at the same time have *sans-serif* style everywhere.

**Comment by pauldhunt** [comment]
@kiwi0fruit roll your own version. the artwork exists. download the tools. Shuffle the alternates in the GOADB, rename the fonts, build with the AFDKO and you’re good to go. good luck! 🍀

**Comment by kiwi0fruit** [comment]
@pauldhunt thanks for encouraging! I guess I'll give it a shot when I test whether Linux file manager uses ligatures of the fonts for displaying. Recently I switched to using Source Sans 3 as a default interface font whenever I can customize a font (it's actually almost everywhere on Linux and in browsers that support Chrome extensions on Android).

**Comment by kiwi0fruit** [comment]
Ubuntu supports font ligatures in all UI (I had problems applying stylistic sets to some UI elements but ligatures word just fine everywhere). So when I would have free time I'll implement the design described above via ligatures of Ia,Iu,Io,Ie,Iy.
