### ISSUE TITLE
Collision avoidance for Lithuanian letters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-sans#251]
I believe there are some necessaries to implement collision avoidance to certain Lithuanian letters as they can overlap each other, for example, in the word Sąjūdis, a-ogonek can overlap _j_ a bit. So you need to implement either kerning or contextual alternates for fix.

**Comment by frankrolf** [comment]
See https://github.com/adobe-fonts/source-serif/issues/115

**Comment by pauldhunt** [comment]
I will wait from some Lithuanian users to file a complaint along with preferred solutions before looking further into this perceived defect.
