### ISSUE TITLE
Issues with source sans 3 and Libreoffice PDF Export

### ISSUE THREAD

**Issue by callegar** [adobe-fonts/source-sans#252]
Documents using the source sans 3 font get exported in PDF by Libreoffice resulting in documents that display OK on machines that include the font but do not print correctly.

Probably an issue in the way Libreoffice embeds the font for the PDF export, but there may be something in the font "triggering" the issue (that does not happen with other TTF and OTF fonts).

So this bug here is mostly to track  https://bugs.documentfoundation.org/show_bug.cgi?id=153905

**Comment by pauldhunt** [comment]
Can you please test with the [latest release](https://github.com/adobe-fonts/source-sans/releases/tag/3.052R) and tell me if this problem persists?

**Comment by callegar** [comment]
It has now been identified that there is a problem in the poppler library that was causing a problem with this font.
Hence, thanks for the new release, but it looks like the font had never been at fault.
I believe that the issue can be closed.
