### ISSUE TITLE
No distinguish between ı́ and í

### ISSUE THREAD

**Issue by sutnistj** [adobe-fonts/source-sans#265]
There're two _i_: oneʼs with a dot — _i_, and without — _ı_. But if I add to them an acute then thereʼre no distinguish between them, because the font changed a dot into an accute.

**Comment by pauldhunt** [comment]
This is expected behavior. In what scenario would you want an i with both the dot and an acute accent? Is there a specific use case or orthography that requires this?

**Comment by moyogo** [comment]
@sutnistj For historical and technical reasons, if you want to have a dot you have to use the combining dot above: i̇́ (0069 LATIN SMALL LETTER I, 0307 COMBINING DOT ABOVE, 0301 COMBINING ACUTE ACCENT)
