### ISSUE TITLE
Regular Italics feel lighter than romans.

### ISSUE THREAD

**Issue by Lululalu** [adobe-fonts/source-sans#277]
It happens specially on the Kindle, as you check on the screenshot below:

![screenshot_2024_06_09T00_20_03-0300](https://github.com/adobe-fonts/source-sans/assets/32398857/2aa41fb3-4ba2-4f6f-bb98-45c2698ff2ea)

**Comment by pauldhunt** [comment]
This a feature, not a bug. The italics are intentionally lighter to provide a high level of differentiation between the upright and italic styles.

**Comment by Lululalu** [comment]
> This a feature, not a bug. The italics are intentionally lighter to provide a high level of differentiation between the upright and italic styles.

Thanks for answer. I got it now.
